# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Future Morlock of the Undercity
email: yamiacat@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 This primitive blog-type website will document my transition from technical-lightweight Eloi to coding-heavyweight Morlock, as I undertake CodeClan's intensive 16 week diploma in Software Development
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mr.jessica.tech/" # the base hostname & protocol for your site
twitter_username: mrjesslynnrose
github_username:  yamiacat

# Build settings
markdown: kramdown
